# seq1 = "ACACACACATGAAATTTAAATTTAAATTTAAATTTTAA"
# seq2 = "ACACACACATGAAATTTATGAAATTTAAATTTAAATTTTAAGGGAAAGGGAAAGAATGTTTAAAGGGTTTAAAGGGTAGGGATGGGGAAATTTGGGTGATGC"
# seq3 = "ATTCCAGACAACATTCGGCTGATTGATCAGGGTTGTTGAAGGTCCAGTGGTACCGCTGCAAAGGAGTAAGAAGGTACCTGGGGTAGACCGCTTAGACCGAGGAGTAGACGACTTCGGAAAGATGGGCAAGGTGAAGCGTCGTCACTTGGTGGCTACCATGACAACGGTTAATGGATTGAGAAAGGACTGCATGAACTTAGTCCCCATTAGCGCGAGATTTGAACTACAGTTACGCCCACTTTCTATCCATTTGGGTTGGTAAACTGTCTATTAATTGGTATCTATGGGTCGGAAATAAGAATTGTTGGCCTCTGACCTAACCTGAGTGTGCGGACCTTCAGAGTGACGAGGTACCGTTCTAGATTATCATGCATAAGTCCGGAAATTAGAACAGTGAATTTGGGAGGCGAAACAGCAGGTCGACTTCCGGGTTTGTTCTTATTTGAATCTACCAAGTCTGATCTCCGTACTCGCTGGCATACGCTGCTATCCTCTGTCCATGCGCTGCTGTCCATGGTCTTGAGGGGCATGCTTGAGGGTAAAAGGCCGTTCCGAGGGCGTGCGGTGTTTTTGCTGACTGTGATCCATATGACGTAACCTCCTCTCTGTTGATTGACAAAGTGAATAATATCTACACTCAACGAAGGATCGATCTCTGTATCTAGGCCCACTTTCGAGTCCCTTCGTCAAAATTCGTGATATGCTTATGGACGGTTTCTCTATTCTTCACTTGCTCCACCCTGACCGGACCTTACTACCTTTCTCATTACAACGGACATGCCGTGTTGAAGTCCGTGGTACCCCATACAAATTCCGTTTGCGGGCCTACACCCCTAAGCGCAGTATCCTTGGTGGCATGGCGTCGACTTGGAGCTTTCTGTTACGGTCCCCATTGCCTATTTTGCCCTGCTACTGACACTCCCGTATGTCCAAACTCACACCGTCCATCACTCACTTACATGACTAGGAACGATTAGGCCAAGCTGTGTACTAACAGAAC"

def find_sequences(seq):
    # print("Sequence length:", len(seq))
    sequences = []
    i = 0
    while i < len(seq) - 2:
        temp_seq = seq[i:i+3]

        if temp_seq == "ATG":
            # print("Found first start pos")
            start_pos = i
            end_pos = -1
            # find end string for this AUG
            for j in range(start_pos, len(seq) - 2, 3):
                temp_seq = seq[j:j+3]

                if temp_seq == "TAA" or temp_seq == "TAG" or temp_seq == "TGA":
                    # print("end")
                    end_pos = j
                    break
            if end_pos != -1:
                # print(seq[start_pos:end_pos+3])
                sequences.append(seq[start_pos:end_pos + 3])
                # now skip this section and find next AUG
                i = end_pos + 2
                # print(i)
            else:
                print("there isn't an ending codon")
        i += 1
    return sequences


seq = input("Enter  sequence: ")
seq = seq.upper()
seqs = find_sequences(seq)
print(len(seqs), seqs)